# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDSwiftStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WDSwiftStudy

  target 'WDSwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WDSwiftStudyUITests' do
    # Pods for testing
  end



end

pod 'SVGAPlayer'
pod 'SnapKit'
